version: '2.4'
services:
 db:
  image: mysql
  container_name: mysqlBank
  environment:
   MYSQL_ROOT_PASSWORD: root
  ports:
    - "3309:3308"
  volumes:
    - java_bank_data:/var/lib/mysql

volumes:
 java_bank_data: